# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d2X0acPk4cvuUBIF9A98Ngq2SqfELWm2

Load the Dataset
"""

import pandas as pd

# Load your dataset
df = pd.read_csv('/content/sample_data/train.csv')

# Preview the first few rows
print(df.head())

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.scatterplot(x='Mileage', y='Price', data=df, alpha=0.6)
plt.title('Scatter Plot of Mileage vs. Price')
plt.xlabel('Mileage (kmpl)')
plt.ylabel('Price (in lakhs)')
plt.grid()
plt.show()

plt.figure(figsize=(10, 6))
average_price_by_fuel = df.groupby('Fuel_Type')['Price'].mean().reset_index()
sns.barplot(x='Fuel_Type', y='Price', data=average_price_by_fuel)
plt.title('Average Price of Used Cars by Fuel Type')
plt.xlabel('Fuel Type')
plt.ylabel('Average Price (in lakhs)')
plt.grid()
plt.show()

plt.figure(figsize=(12, 6))
sns.boxplot(x='Owner_Type', y='Price', data=df)
plt.title('Box Plot of Used Car Prices by Owner Type')
plt.xlabel('Owner Type')
plt.ylabel('Price (in lakhs)')
plt.grid()
plt.xticks(rotation=45)  # Rotate x-axis labels if necessary
plt.show()